AWS/Azure/GCloud: Allow port ranges and per machine rules
EnterpriseDB/edb-terraform pull request #69
Opened 2023-06-13 13:56 UTC by bryan-bar

Allow for port ranges to be defined with an optional `to_port` key, under any port rule.

Fixes:
* GCloud spec updated to allow machine specific port rules, mimicking AWS security groups 
  * Requires unique naming within security module
* Azure spec updated to allow machine specific port rules, mimicking AWS security groups
  * Each service/region port rule added to a machine if it has additional port rules so that a network interface security group can be used instead of the default security group
    * avoids conflicting priorities as each interface will have its own set of rules
    * if a machine has no port rules, it will skip creating the network interface security group and instead default to the subnets security group

Ref: https://github.com/EnterpriseDB/edb-terraform/pull/47

2023-06-13 14:02 UTC, mw2q requested changes
This is another instance where I'd like to see separate commits per cloud service.  Perhaps not necessarily more refined than that.

2023-06-13 15:17 UTC, bryan-bar commented
@mw2q We haven't been using `issues`. Would it be better if we created issues per bug/feature and then PRs per cloud provider that implement it going forward? Some commits are exactly the same across the 3 providers but there is the occasional implementation detail needed per provider.

2023-06-13 15:25 UTC, mw2q commented
> @mw2q We haven't been using `issues`. Would it be better if we created issues per bug/feature and then PRs per cloud provider that implement it going forward? Some commits are exactly the same across the 3 providers but there is the occasional implementation detail needed per provider.

I don't think that's necessary in this case.  I think it's ok for the issue to be "allow port ranges etc".  But then the branch have the separate commits in one PR.  We want them to all merge in at the same time, right?

2023-06-13 16:14 UTC, bryan-bar commented
> > @mw2q We haven't been using `issues`. Would it be better if we created issues per bug/feature and then PRs per cloud provider that implement it going forward? Some commits are exactly the same across the 3 providers but there is the occasional implementation detail needed per provider.
> 
> I don't think that's necessary in this case. I think it's ok for the issue to be "allow port ranges etc". But then the branch have the separate commits in one PR. We want them to all merge in at the same time, right?

Yes, merged all at once. In most cases, the "feature" should be completed across all providers at once to minimize any provider specific implementations and to catch places where we can abstract it from the user.
This PR will be an exception then since I had made the changes for AWS first and Azure/Gcloud security modules are "fixed" to match AWS security groups functionality from PR 47.

2023-06-21 14:55 UTC, mw2q approved these changes
Thanks for breaking that up.  The changes looks sane to me. :)

2023-06-22 03:39 UTC, merged